#ifndef SHADER_STREAMS_H
#define SHADER_STREAMS_H

#ifdef WIN32

class ShaderStreamId
{
public:
	ShaderStreamId(const char* streamTypeSemantic, uint32 idx) //uint32 streamType, uint32 idx) 
		:
	m_streamTypeSemantic(streamTypeSemantic),
	m_index(idx)
	{
	}

	const char* m_streamTypeSemantic;
	//uint32 m_streamType;
	uint32 m_index;
};


#define TEXCOORD_STREAM_IDX(x) ShaderStreamId("TEXCOORD", x)
#define COLOUR_STREAM_IDX(x) ShaderStreamId("COLOR",x)
#define TANGENT_STREAM_ID ShaderStreamId("TANGENT", 0)

#else

#define TEXCOORD_STREAM_IDX(x) TEXCOORD##x
#define COLOUR_STREAM_IDX(x) COLOR##x
#define TANGENT_STREAM_ID TANGENT

#endif

#define TANGENT_STREAM TANGENT_STREAM_ID
#define COLOUR_STREAM COLOUR_STREAM_IDX(0)
#define BLENDINDICES_STREAM COLOUR_STREAM_IDX(1)
#define UV_STREAM TEXCOORD_STREAM_IDX(0)
#define SMOOTHED_NORMAL_STREAM TEXCOORD_STREAM_IDX(1)
#define TIME_STREAM TEXCOORD_STREAM_IDX(2)
#define WEIGHTS_STREAM TEXCOORD_STREAM_IDX(3)
#define DIFFUSE_UV_STREAM TEXCOORD_STREAM_IDX(4)
#define INSTANCE_POSSIZE_STREAM TEXCOORD_STREAM_IDX(5)
#define INSTANCE_POSTIME_STREAM TEXCOORD_STREAM_IDX(5)
#define INSTANCE_TRANSFORM0_STREAM TEXCOORD_STREAM_IDX(5)
#define INSTANCE_ROTSIZE_STREAM TEXCOORD_STREAM_IDX(6)
#define INSTANCE_ROT_STREAM TEXCOORD_STREAM_IDX(6)
#define INSTANCE_AXISANGLE_STREAM TEXCOORD_STREAM_IDX(6)
#define INSTANCE_TRANSFORM1_STREAM TEXCOORD_STREAM_IDX(6)
#define INSTANCE_SCALE_STREAM TEXCOORD_STREAM_IDX(7)
#define INSTANCE_TRANSFORM2_STREAM TEXCOORD_STREAM_IDX(7)

#endif
